---
title: "FastDemux"
author: "Roger Pique-regi"
format: revealjs
editor: visual
---

## Introduction

Compared to other single cell de-multiplexing approaches, Fastdemux is based on diagonal linear discriminant (DLDA) type of approach. The input is a a vcf file, a bam file from 10X cellranger output, and a list of barcodes. We can then build a DLDA for each barcode $b$ and individual $n$ as:

$$
g_n^b=\sum_{l=1}^L \sum_{k=1}^{K^b_l} \frac{d_{nl} - 2 q_l}{\sqrt{2 q_l (1-q_l)}} \frac{X_{bk} - q_l}{\sqrt{q_l (1-q_l)}}
$$

## DLDA for singlets

For each barcode $b$ and individual $n$:

$$
g_n^b=\sum_{l=1}^L \sum_{k=1}^{K^b_l} \frac{d_{nl} - 2 q_l}{\sqrt{2 q_l (1-q_l)}} \frac{X_{bk} - q_l}{\sqrt{q_l (1-q_l)}}
$$

-   Note that we treat each read $X_{bk}$ as independent and it equals 1 if it is the alternate allele, and 0 otherwise.
-   For each barcode $b=1, ..., B$ we gather all reads $k=1, ..., K^b_l$ on genetic variants: $l=1, ..., L$.
-   For each individual $n=1,...,N$ we also have the dosage $d_{nl}$ and alternate allele frequency $q_l=\sum_n^Nd_{nl}$

## DLDA for singlets

For each barcode $b$ and individual $n$:

$$
g_n^b=\sum_{l=1}^L \sum_{k=1}^{K^b_l} \frac{d_{nl} - 2 q_l}{\sqrt{2 q_l (1-q_l)}} \frac{X_{bk} - q_l}{\sqrt{q_l (1-q_l)}}
$$

Note that left and right side are normalized to have mean 0 and variance 1.

## DLDA for doublets

For each barcode $b$ and individual $n$ and $n'$:

$$
g_{nn'}^b=\sum_{l=1}^L \sum_{k=1}^{K^b_l} \frac{\frac{d_{nl}+d_{n'l}}{2} - 2 q_l}{\sqrt{q_l (1-q_l)}} \frac{X_{bk} - q_l}{\sqrt{q_l (1-q_l)}}
$$

Note that the variance of the weight for the doublet is $\sqrt{2}$ lower than of a singlet.

## DLDA for singlets

After adding all the reads at location $l$, $A^b_l= \sum_{k=1}^{K^b_l} X_{bk}$ $$
g_n^b=\sum_{l=1}^L \sum_{k=1}^{K^b_l} \frac{d_{nl} - 2 q_l}{\sqrt{2 q_l (1-q_l)}} \frac{X_{bk} - q_l}{\sqrt{q_l (1-q_l)}}
$$

$$
g_n^b=\sum_{l=1}^L \frac{d_{nl} - 2 q_l}{\sqrt{2} q_l (1-q_l)}  \sum_{k=1}^{K^b_l} {X_{bk} - q_l}
$$

$$
g_n^b=\sum_{l=1}^L \frac{d_{nl} - 2 q_l}{\sqrt{2} q_l (1-q_l)} \left(A^b_{l} - K^b_l q_l\right)
$$

## DLDA for doublets

Similarly for doublets: $$
g_{nn'}^b=\sum_{l=1}^L \sum_{k=1}^{K^b_l} \frac{\frac{d_{nl}+d_{n'l}}{2} - 2 q_l}{\sqrt{q_l (1-q_l)}} \frac{X_{bk} - q_l}{\sqrt{q_l (1-q_l)}}
= \sum_{l=1}^L  \frac{\frac{d_{nl}+d_{n'l}}{2} - 2 q_l}{q_l (1-q_l)}  \left(A^b_{l} - K^b_l q_l\right)
$$ but now we can express it in terms of singlets: $$
g_{nn'}^b=\sum_{l=1}^L  \frac{ \frac{d_{nl} - 2 q_l}{2} + \frac{d_{n'l} -  2 q_l}{2} }{q_l (1-q_l)}  \left(A^b_{l} - K^b_l q_l\right) = \sqrt{2} \frac{g_{n}^b+g_{n'}^b}{2}
$$

## DLDA for $M$-let

$$
g_{n_1,...,n_M}^b=\sum_{l=1}^L  \frac{ \sum_m^M \frac{d_{n_m,l} - 2 q_l}{M}}{\sqrt{2/M} q_l (1-q_l)}   \left(A^b_{l} - K^b_l q_l\right)
$$

$$
g_{n_1,...,n_M}^b=\frac{\sqrt{M}}{M} \sum_m^M g_{n_m}^b
$$

## Code

When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```
